backend/config/routes.rb
Backend::Application.routes.draw do
	resources :roles do
		collection do
			post 'assign_permission'
			delete 'revoke_permission'
		end
	end
	resources :permissions, :only => ['index']
	# user and authentication related routes start
	resources :users do
		collection do
			get 'logged_in'
			post 'sign_in' => 'users#user_signin'
			post 'change_password'
			post 'forgot_password'
			get 'resend_confirmation'
			post 'sign_up' => 'users#user_signup'
			get 'sample_user_csv'
			post 'upload_user_csv'
			post 'assign_role'
			delete 'revoke_role'
		end

	end
	devise_for :users, path: 'auth', controllers: {
											 confirmations: 'users/confirmations',
											 passwords: 'users/passwords',
											 registrations: 'users/registrations',
											 sessions: 'users/sessions',
									 }
	#For setting routes devise_scope must be used
	devise_scope :user do
		get 'sign_out' => 'users/sessions#destroy'
		get 'sign_in' => 'users/sessions#new'
		get 'sign_up' => 'users/registrations#new'

	end

	get '/login' => 'home#login'
	# You can have the root of your site routed with "root"
	root 'home#index'
end

backend/app/models/role.rb
class Role < AppBaseModel
	has_and_belongs_to_many :permissions, -> { uniq }
	has_and_belongs_to_many :users, -> { uniq }
	validates :name, :presence => true, :uniqueness => true
end

backend/app/controllers/roles_controller.rb
class RolesController < ApplicationController
	load_and_authorize_resource
	respond_to :html

	def assign_permission
		if params[:permission_id] == "" || params[:permission_id].nil? || params[:role_id] == "" || params[:role_id].nil?
			head :unprocessable_entity
			return
		end
		@role=Role.find(params[:role_id]) rescue nil
		@permission=Permission.find(params[:permission_id]) rescue nil
		if @permission.nil? || @role.nil?
			head :precondition_failed
			return
		end
		@role.permissions << @permission
		redirect_to role_path @role
	end

	def revoke_permission
		if params[:permission_id] == "" || params[:permission_id].nil? || params[:role_id] == "" || params[:role_id].nil?
			head :unprocessable_entity
			return
		end
		@role=Role.find(params[:role_id]) rescue nil
		@permission=Permission.find(params[:permission_id]) rescue nil
		if @permission.nil? || @role.nil?
			head :precondition_failed
			return
		end
		@role.permissions.destroy @permission
		redirect_to role_path @role
	end

	def index
		@roles = Role.all
		respond_with(@roles)
	end

	def show
		@role = Role.find(params[:id])
		respond_with(@role)
	end

	def new
		@role = Role.new
		respond_with(@role)
	end

	def edit
	end

	def create
		@role = Role.new(role_params)
		@role.save
		respond_with(@role)
	end

	def update
		@role.update(role_params)
		respond_with(@role)
	end

	def destroy
		@role.destroy
		respond_with(@role)
	end

	private
	def role_params
		params.require(:role).permit(:name, :description)
	end
end

backend/app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <%= render :partial => 'layouts/form_errors', :object => @role.errors %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/roles/_permission_form.html.erb
<div id="role_form" class="centered-card clearfix">
  <%= form_tag(assign_permission_roles_path, method: "post") do %>
    <%= hidden_field_tag :role_id, @role.id %>
    <div class="field">
      <%= label_tag(:permission, "Permission") %>
      <%= collection_select(nil, :permission_id, Permission.all, :id, :title, {:prompt => "Select Role"}, {:multiple => false}) %>
    </div>
    <div class="actions">
      <%= submit_tag("Assign permission", :class => "text btn btn-primary") %>
    </div>
  <% end %>
</div>

backend/app/views/roles/_role_list.html.erb
<div class="manage-section">
  <h1>Listing Roles</h1>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Destroy', revoke_role_users_path(:user_id => @user.id,:role_id =>  role.id), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

backend/app/views/roles/_role_permissions.html.erb
<h3>Permissions</h3>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Title</th>
    <th>Action</th>
    <th>Subject</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @role.permissions.each do |permission| %>
    <tr>
      <td><%= permission.title %></td>
      <td><%= permission.action %></td>
      <td><%= permission.subject %></td>
      <td><%= link_to 'Remove', revoke_permission_roles_path(:role_id => @role.id, :permission_id => permission.id), :data => {confirm: 'Are you sure?'}, method: :delete, :class => 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

backend/app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

backend/app/views/roles/index.html.erb
<div class="manage-section">
<h1>Listing Roles</h1>

<%= link_to 'New Role', new_role_path %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

backend/app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

backend/app/views/roles/show.html.erb
<div class="manage-section container-fluid">
  <div class="row-fluid clearfix">
    <div class="col-md-4">
      <%= link_to 'Edit', edit_role_path(@role), :class => 'btn btn-info' %>
      <%= link_to 'Back', roles_path, :class => 'btn btn-info' %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="col-md-4">
      <table class="table table-bordered">
        <tr>
          <td>Role Name:</td>
          <td> <%= @role.name %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= @role.description %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="field clearfix">
    <button type="button" id="b4" class="btn btn-primary pull-right" data-toggle="modal" data-target="#permissionModal">
      Add New Permission
    </button>
  </div>
  <div class="modal fade in" id="permissionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add new Permission</h4>
        </div>
        <div class="modal-body">
          <%= render 'roles/permission_form' %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= render 'role_permissions' %>
  </div>
</div>