backend/config/routes.rb
Backend::Application.routes.draw do
	resources :roles do
		collection do
			post 'assign_permission'
			delete 'revoke_permission'
		end
	end
	resources :permissions, :only => ['index']
	# user and authentication related routes start
	resources :users do
		collection do
			get 'logged_in'
			post 'sign_in' => 'users#user_signin'
			post 'change_password'
			post 'forgot_password'
			get 'resend_confirmation'
			post 'sign_up' => 'users#user_signup'
			get 'sample_user_csv'
			post 'upload_user_csv'
			post 'assign_role'
			delete 'revoke_role'
		end

	end
	devise_for :users, path: 'auth', controllers: {
											 confirmations: 'users/confirmations',
											 passwords: 'users/passwords',
											 registrations: 'users/registrations',
											 sessions: 'users/sessions',
									 }
	#For setting routes devise_scope must be used
	devise_scope :user do
		get 'sign_out' => 'users/sessions#destroy'
		get 'sign_in' => 'users/sessions#new'
		get 'sign_up' => 'users/registrations#new'

	end

	get '/login' => 'home#login'
	# You can have the root of your site routed with "root"
	root 'home#index'
end

backend/app/views/layouts/_form_errors.html.erb
<% if form_errors.any? %>
	<div class="form-errors alert alert-danger">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <h3><%= pluralize(form_errors.count, "error") %> prohibited this record from being saved:</h3>
	  <ul>
		<% form_errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	  </ul>
	</div>
<% end %>

backend/app/views/layouts/_header.html.erb
<div class="name">
	<%= link_to 'QUIKCHEX', root_url%>
</div>

<%= yield :app_header %>
<% if current_user %>
	<div id="user-info">
		Welcome <%= current_user.fullname %>
		<%= link_to 'Logout Now', sign_out_path %>
	</div>
<% end %>

backend/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

backend/app/views/layouts/_modal.html.erb
<div class="modal fade" id="global_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal header to be set by JS</h4>
      </div>
      <div class="modal-body">
        This body html will be replaced by the JS dynamically
      </div>
    </div>
  </div>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Backend" %></title>
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Backend" %>">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= yield 'head' %>
</head>
<body>
	<header id="app-header">
		<%= render 'layouts/header' %>
	</header>
	<main role="main">
		<div id="main-wrapper">
			<section id="main-content">
				<%= render 'layouts/messages' %>
				<%= yield %>
			</section>
		</div>
	</main>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

backend/app/views/layouts/error401.html.erb
<h1>Authenticated User Only</h1>
<p>You are not authorized to do this action</p>

backend/app/views/layouts/modal_layout.html.erb
<section id="modal-help-wrapper" class="help-wrapper">
  <div class="clearfix">
    <a href="#" onclick="ce_ec.modal.toggleHelp()">Close <%= fa_icon 'times' %></a>
    <a id="briefDetailedToggle" onClick="ce_ec.modal.toggleDetailedHelp()" class='pull-right' href="#">Detailed help</a>
  </div>
  <%= yield :modal_help %>
</section>
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <a href="#" class='close' title="help" onclick="ce_ec.modal.toggleHelp()"><%= fa_icon 'question-circle' %></a>
    <h4 class="modal-title" id="myModalLabel">
      <%= yield :modal_title %>
    </h4>
  </div>
  <div class="modal-body">
    <%= yield %>
  </div>
</div>