backend/config/routes.rb
Backend::Application.routes.draw do
	resources :roles do
		collection do
			post 'assign_permission'
			delete 'revoke_permission'
		end
	end
	resources :permissions, :only => ['index']
	# user and authentication related routes start
	resources :users do
		collection do
			get 'logged_in'
			post 'sign_in' => 'users#user_signin'
			post 'change_password'
			post 'forgot_password'
			get 'resend_confirmation'
			post 'sign_up' => 'users#user_signup'
			get 'sample_user_csv'
			post 'upload_user_csv'
			post 'assign_role'
			delete 'revoke_role'
		end

	end
	devise_for :users, path: 'auth', controllers: {
											 confirmations: 'users/confirmations',
											 passwords: 'users/passwords',
											 registrations: 'users/registrations',
											 sessions: 'users/sessions',
									 }
	#For setting routes devise_scope must be used
	devise_scope :user do
		get 'sign_out' => 'users/sessions#destroy'
		get 'sign_in' => 'users/sessions#new'
		get 'sign_up' => 'users/registrations#new'

	end

	get '/login' => 'home#login'
	# You can have the root of your site routed with "root"
	root 'home#index'
end

backend/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

backend/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

backend/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

backend/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :firstname
    devise_parameter_sanitizer.for(:sign_up) << :lastname
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

backend/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
      user = User.where(:email => params[:user][:email])[0]
      login_status = :unauthorized
      message = 'Not Authorized'
      if user.nil?
        message = 'Sorry this User does not exist.'
      # elsif !user.active?
      #   message = 'Cannot login because user is not active.'
      elsif user.valid_password?(params[:user][:password]) #Check the password validtity
        sign_in(:user, user) #Sign in the user
        unless current_user.nil?
          login_status = :success
          message = 'Sign in successful'
        end
      else
        message = 'Password Invalid'
      end
      if login_status == :success
        respond_to do |format|
          format.json { render json: {:message => message} }
          format.html { redirect_to root_path }
        end
      else
        respond_to do |format|
          format.json {
            render json: {:message => message}
          }
          format.html {
            flash[:alert] = message
            redirect_to new_user_session_path
          }
        end
      end    
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

backend/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'oauth'
	require 'nokogiri'
	respond_to :html, :json

	def index
		authorize! :read, User
		@users=User.search(params)
	end

	def assign_role
		authorize! :assign_role, User
		if params[:user_id] == "" || params[:user_id].nil? || params[:role_id] == "" || params[:role_id].nil?
			head :unprocessable_entity
			return
		end
		@user = User.find(params[:user_id]) rescue nil
		@role = Role.find(params[:role_id]) rescue nil
		if @user.nil? || @role.nil?
			head :precondition_failed
			return
		end
		@user.roles << @role
		redirect_to user_path @user
	end

	def revoke_role
		authorize! :revoke_role, User
		if params[:user_id] == "" || params[:user_id].nil? || params[:role_id] == "" || params[:role_id].nil?
			head :unprocessable_entity
			return
		end
		@user = User.find(params[:user_id]) rescue nil
		@role = Role.find(params[:role_id]) rescue nil
		if @user.nil? || @role.nil?
			head :precondition_failed
			return
		end
		@user.roles.destroy @role
		redirect_to user_path @user
	end

	def show
		@user = User.find(params[:id])
		authorize! :read, @user
		@roles = @user.roles
	end

	def new
		@user= User.new
		authorize! :create, @user
		respond_with(@user)
	end

	def create
		@user=User.new(user_params)
		authorize! :create, @user
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user=User.find(params[:id])
		authorize! :update, @user
	end

	def update
		@user=User.find(params[:id])
		authorize! :update, @user
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def logged_in
		#This method will return the current logged in user if there is any.
		respond_to do |format|
			if current_user
				format.json { render json: current_user }
			else
				format.json { render json: {:message => "Nobody logged In"}, status: :ok }
			end
		end
	end

	def user_signin
		#This method will handle the sign in of a user through an ajax request.
		#The user from the frontend will enter his/her credentials in the modal. The Ember app will then make an ajax request to our rails app
		#with the data entered by the user. Then we will authenticate the user through devise and set the current_user.
		# If successfully authenticated we will respond with the user_id to the frontend otherwise we will respond with errors
		# encountered.
		if request.method != 'POST' or !request.xhr?
			render json: {}, :status => :not_acceptable
		else
			sign_out(current_user) if current_user
			user = User.find_by_email(params[:user][:email])
			if user.nil?
				respond_to do |format|
					format.json { render json: {:message => "Sorry this User does not exist."} }
				end
			else
				if user.valid_password?(params[:user][:password]) #Check the password validtity
					sign_in(:user, user) #Sign in the user
					if current_user
						respond_to do |format|
							format.json { render json: {:message => "Sign in successful"} }
						end
					end
				else
					respond_to do |format|
						format.json { render json: {:message => "Password  invalid"} }
					end
				end
			end
		end
	end

	def user_signup
		#This method will handle the user sign up through an ajax request.
		#The user from the frontend will enter details in the modal. The Ember app will then make an ajax request to our rails app
		#with the data entered by the user. Then we will create the user in this method. If successfully created the response will
		#contain msg with value 1. Otherwise we will send the errors encountered in user model creation in JSON format to frontend.
		#This method assumes all the data validations have been done by the frontend application. Devise also will do another set of
		#validations and checks before creating the user.
		if request.method != 'POST' or !request.xhr?
			render json: {}, :status => :not_acceptable
		else
			user = User.new(user_params)
			message_success= {:msg => 1}
			if user.save
				sign_out(current_user) if current_user
				sign_in(:user, user)
				render json: {:msg => 1}, status: :ok
			else
				errors = user.errors
				render json: errors.messages, status: :ok
			end
		end
	end

	def resend_confirmation
		respond_to do |format|
			if current_user and current_user.confirmed_at.nil?
				current_user.send_confirmation_instructions
				format.json { render json: {:message => "Sent"} }
			else
				if !current_user.confirmed_at.nil?
					format.json { render json: {:message => "Already Confirmed"} }
				end
			end
		end
	end

	def forgot_password_user
		user = User.find_by_email(params[:email])
		respond_to do |format|
			if !user.nil?
				if user.send_reset_password_instructions
					format.json { render json: {:message => "Password reset instructions have been sent to the email."} }
				end
			else
				format.json { render json: {:message => "User does not exist."} }
			end
		end
	end

	def change_password
		if params[:user]
			if current_user.valid_password? params[:user][:oldPassword]
				current_user.password=params[:user][:newPassword]
				#current_user.reset_password_token=User.reset_password_token
				current_user.reset_password_sent_at = Time.now
				if current_user.save
					#Whenever user changes password we recompute the md5hash so that previous hashes stored on devices don't work.
					#current_user.generate_md5hash
					#Notifier.delay.change_password(current_user)
					respond_to do |format|
						format.json { render json: {:status => "Password change successful. Please login again with new password."} }
					end
				else
					respond_to do |format|
						format.json { render json: {:status => "There was some error on our side. Please try again later."} }
					end
				end
			else
				respond_to do |format|
					format.json { render json: {:status => "It seems you entered the wrong old password"} }
				end
			end

		else
			respond_to do |format|
				format.json { render :json => {:status => "Error:Not a valid User"} }
			end
		end

	end


	def facebook
		if params[:access_token].nil?
			@user={'status' => 'error'}
			respond_to do |format|
				format.json { render :json => @user }
			end
		else
			token=params[:access_token]

			uri = URI.parse('https://graph.facebook.com/me')
			args = {:access_token => token, :fields => 'id,first_name,last_name,email'}

			uri.query = URI.encode_www_form(args)
			http = Net::HTTP.new(uri.host, uri.port)
			http.use_ssl = true
			begin
				request = Net::HTTP::Get.new(uri.request_uri)
				response = http.request(request)

				if response.nil?
					@user={'status' => 'error'}
					respond_to do |format|
						format.json { render :json => @user }
					end
					return
				else
					parsed_data= JSON.parse response.body
				end

				unless parsed_data.has_key?('id') and parsed_data.has_key?('email') and parsed_data.has_key?('first_name') and parsed_data.has_key?('last_name')
					raise Exception
				end

			rescue
				@user={'status' => 'error'}
				respond_to do |format|
					format.json { render :json => @user }
				end
				return
			end

			uid=parsed_data['id']
			email=parsed_data['email'].downcase
			firstname=parsed_data['first_name']
			lastname=parsed_data['last_name']

			@user = get_auth_user(uid, firstname, lastname, email, token, 'facebook')
			respond_to do |format|
				format.json { render :json => @user }
			end
		end
	end

	def google
		if params[:access_token].nil?
			@user={'status' => 'error'}
			respond_to do |format|
				format.json { render :json => @user }
			end
		else
			token=params[:access_token]
			uri = URI.parse('https://www.googleapis.com/oauth2/v1/userinfo')
			args = {:access_token => token}
			uri.query = URI.encode_www_form(args)
			http = Net::HTTP.new(uri.host, uri.port)
			http.use_ssl = true

			begin
				request = Net::HTTP::Get.new(uri.request_uri)
				response = http.request(request)

				if response.nil?
					@user={'status' => 'error'}
					respond_to do |format|
						format.json { render :json => @user }
					end
					return
				else
					parsed_data= JSON.parse response.body
				end

				unless parsed_data.has_key?('id') and parsed_data.has_key?('email')
					raise Exception
				end
				uid=parsed_data['id']
				email=parsed_data['email'].downcase

				uauth=UserAuth.where({:uid => uid, :provider => 'google'}).first
			rescue
				@user={'status' => 'error'}
				respond_to do |format|
					format.json { render :json => @user }
				end
				return
			end
			if uauth.nil?
				user=User.find_by_email email
				if user.nil?
					quri = URI.parse("https://www.googleapis.com/plus/v1/people/#{uid}?access_token=#{token}")
					#qargs = {:key=> 'AIzaSyA3AogvKKttZlriHJmGqTLnVJa3UWGHT14',:fields=> 'name'}

					#quri.query = URI.encode_www_form(qargs)
					qhttp = Net::HTTP.new(quri.host, quri.port)
					qhttp.use_ssl = true
					qhttp.verify_mode = OpenSSL::SSL::VERIFY_NONE

					qrequest = Net::HTTP::Get.new(quri.request_uri)
					begin
						qresponse = qhttp.request(qrequest)
						if qresponse.nil?
							@user={'status' => 'error'}
							respond_to do |format|
								format.json { render :json => @user }
							end
							return
						else
							parsed_response=JSON.parse qresponse.body
						end
						unless parsed_response.has_key?('name') and parsed_response['name'].has_key?('givenName') and parsed_response['name'].has_key?('familyName')
							raise Exception
						end
					rescue
						@user={'status' => 'error'}
						respond_to do |format|
							format.json { render :json => @user }
						end
						return
					end

					firstname=parsed_response['name']['givenName']
					lastname=parsed_response['name']['familyName']

					@user=User.create({:firstname => firstname, :lastname => lastname, :email => email})
					@user.confirm!
				else
					@user=user
				end

				UserAuth.create({:uid => uid, :provider => 'google', :user_id => @user.id, :token => token})
			else
				@user=uauth.user
			end

			sign_out current_user if current_user

			sign_in @user
			respond_to do |format|
				format.json { render :json => @user }
			end
		end

backend/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <!--rendering form errors via a partial-->
  <%= render :partial => 'layouts/form_errors', :object => @user.errors %>
  <div class="field">
    <%= f.label :uid, :class => "Ulabel" %>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :firstname, "First Name", :class => "Ulabel" %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, "Last Name", :class => "Ulabel" %>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email, "Email_id", :class => "Ulabel" %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :status, :class => "Ulabel" %>
    <%= f.check_box('status', {}, 'active', 'inactive') %>
  </div>
  <div class="actions">
    <%= f.submit :class => "text btn btn-primary" %>
  </div>
<% end %>

backend/app/views/users/_formedit.html.erb
<%= form_for(@user) do |f| %>
    <!--rendering form errors via a partial-->
    <%= render :partial =>'layouts/form_errors', :object => @user.errors %>
    <div class="field">
      <%= f.label :uid , :class=>"Ulabel" %>
      <%= f.text_field :uid%>
    </div>
    <div class="field">
      <%= f.label :firstname, "First Name" , :class=>"Ulabel" %>
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname,"Last Name" , :class=>"Ulabel" %>
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :email, "Email_id", :class=>"Ulabel" %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :status , :class=>"Ulabel"%>
      <%= f.check_box('status',{},'active','inactive')%>
    </div>
    <div class="actions">
      <%= f.submit :class=>"text btn btn-primary" %>
    </div>
<% end %>

backend/app/views/users/_nav_menu.html.erb
<ul id="generic_master_menu" class="sub-menu">
  <li><%= link_to users_path do %>Users <span class="icon"><%= fa_icon 'chevron-right' %></span>
    <% end %></li>
  <li><%= link_to roles_path do %>Roles <span class="icon"><%= fa_icon 'chevron-right' %></span>
    <% end %></li>
  <li><%= link_to permissions_path do %>Permissions <span class="icon"><%= fa_icon 'chevron-right' %></span>
    <% end %></li>
</ul>

backend/app/views/users/_role_form.html.erb
<div id = "role_form" class="centered-card clearfix">
  <%= form_tag(assign_role_users_path, method: "post") do %>
    <%= hidden_field_tag :user_id, @user.id %>
    <div class="field">
      <%= label_tag(:role, "Role") %>
      <%= collection_select(nil, :role_id, Role.all, :id, :name, {:prompt => "Select Role"}, {:multiple => false}) %>
    </div>
    <div class="actions">
      <%= submit_tag("Assign Role", :class=>"text btn btn-primary")%>
    </div>
  <% end %>
</div>

backend/app/views/users/callback.html.erb
<script>
	app = window.opener.App;
	con = app.__container__.lookup('controller:loginmodal');

	status = "<%= @user ? "success" : "error" %>";

	con.linkedinLoginComplete(status);
	window.close() ;

</script>

backend/app/views/users/edit.html.erb
<div id="unit-form" class="clearfix container-fluid centered-card" >
<h1> EDITING details of USER</h1>
 <%= render "formedit" %>
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', user_path %>
</div>

backend/app/views/users/index.html.erb
<div class="manage-section">
 <% if @users.present? %>
  <h1>All Users</h1>
  <%= form_tag users_path, :method => 'get', :id => "units_search" do %>
      <p>
        <%= text_field_tag :search_name, params[:search_name],placeholder: "User Name",:class=>"U-search" %>
        <%= text_field_tag :search_uid, params[:search_uid],placeholder: "User uid",:class=>"U-search" %>
        <%= submit_tag "Search", :Name => nil,:class=>"U-searchB btn btn-primary" %>
      </p>
  <% end %>
<%= link_to "NEW USER", new_user_path,:class=>"U-button btn btn-primary" %>
  <table class="table table-bordered">
    <thead>
    <tr>
    <th>UID</th>
    <th>Name</th>
    <th>Email_Id</th>
    <th>Status</th>
    <th colspan = "3">Actions</th>
   </tr>
    </thead>
    <% @users.each do |u| %>
     <tbody>
      <tr>
        <td><%= u.uid%></td>

    <td><%= u.fullname %></td>

    <td><%= u.email %></td>
        <td><%= u.status%></td>
        <td><%= link_to "SHOW" , user_path(u),:class=>"btn btn-primary" %></td>
    <td><%= link_to "EDIT" , edit_user_path(u),:class=>"btn btn-danger" %></td>
  </tr>
      <% end %>
    </tbody>
</table>
  <% else %>
  <%= form_tag users_path, :method => 'get', :id => "units_search" do %>
      <p>
        <%= text_field_tag :search_name, params[:search_name],placeholder: "User Name",:class=>"U-search" %>
        <%= text_field_tag :search_uid, params[:search_uid],placeholder: "User uid",:class=>"U-search" %>
        <%= submit_tag "Search", :Name => nil,:class=>"U-searchB btn btn-primary" %>
      </p>
  <% end %>
  <%= link_to "NEW USER", new_user_path,:class=>"U-button btn btn-primary" %>
  <%= link_to "BACK", users_path,:class=>"U-button btn btn-primary" %>

  <h4>No User found  for search <%=params[:search]%></h4>

 <% end %>
</div>

backend/app/views/users/new.html.erb
<div id="unit-form" class="clearfix container-fluid centered-card" >
  <h3>Sign Up</h3>
  <%= render 'form' %>
</div>

backend/app/views/users/show.html.erb
<div class="manage-section container-fluid">
  <div class="row-fluid clearfix">
    <h2 class="col-md-8">Details </h2>

    <div class="col-md-4">
      <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-primary' %>
      <%= link_to 'Back', users_path(@users), :class => 'btn btn-primary' %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="col-md-4">
      <table class="table table-bordered">
        <tr>

          <td>uid:</td>
          <td> <%= @user.uid %></td>
        </tr>
        <tr>
          <td>first name:</td>
          <td><%= @user.firstname %></td>
        </tr>
        <tr>
          <td>Last name</td>

          <td><%= @user.lastname %></td>
        </tr>

        <tr>
          <td>Email_id:</td>

          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Status</td>
          <td> <%= @user.status %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="field clearfix">
    <button type="button" id="b3" class="btn btn-primary pull-right" data-toggle="modal" data-target="#roleModal">
      Add New Role
    </button>
  </div>

  <div class="modal fade in" id="roleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add new Role</h4>
        </div>
        <div class="modal-body">
          <%= render 'users/role_form' %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= render 'roles/role_list' %>
  </div>
</div>

backend/app/views/users/twitter_callback.html.erb
<% if !@user %>
	please enter email address to continue
	<%= form_tag '/auth/twitter/email_twitter_callback' do %>

		<%= label_tag :email %>
		<%= text_field_tag :email, params[:email] %>

		<%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
	<% end %>
<% end %>

<script>
	app = window.opener.App;
	con = app.__container__.lookup('controller:loginmodal');

	status = "<%= @oauth_error ? 'error' : (@user ? "success" : "") %>";

	if(status != ""){
		con.twitterLoginComplete(status);
		window.close() ;
	}

</script>